server:
  port: 6070

spring:
  application:
    name: Concerno-A-Citizen-Grievance-Redressal-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/complaint_mgmt_db
    username: root
    password: Anu@sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: user
      password: user
